create table person(
    id int generated by default as identity primary key,
    full_name varchar(255) not null unique,
    birth_year int check (birth_year > 1900)
);

create table book(
    id int generated by default as identity primary key,
    person_id int references person(id) on delete set null,
    name varchar(255) not null,
    author varchar(255) not null,
    year int check (year > 0)
);